# <h1>Networks:- Lab 1

#### 1. Explaination
 Adjaceny matrix and adjanceny list explanation and their advantages and disadvantages (page: 33 & 34) in the book<br/>


#### 2. Adjacency List


In [1]:
function constructAdjListFromFile(fname)
    data=readcsv(fname,Int)
    n=maximum(data) 
    m=size(data,1)
    A=Array(Array{Int},n) 
    for i=1:n A[i]=[] end # Initialization of adjacency list

    for arcIndx=1:m
        i,j=data[arcIndx,:]
        push!(A[i],j)
    end
    A
end


constructAdjListFromFile (generic function with 1 method)

In [13]:
adjList = constructAdjListFromFile("Lab_1_data.csv")

6-element Array{Array{Int64,N},1}:
 [2]    
 [4,5]  
 [2,1]  
 [6,5]  
 Int64[]
 [5]    

#### 3. Adjacency Matrix

In [2]:
function constructAdjMatFromFile(fname)
    data=readcsv(fname,Int)
    n=maximum(data) 
    M=zeros(Bool,n,n)
    m=size(data,1)
    for arcIndx=1:m
        i,j=data[arcIndx,:]
        M[i,j]=true
    end
    M
end

constructAdjMatFromFile (generic function with 1 method)

In [3]:
adjMat = constructAdjMatFromFile("Lab_1_data.csv")

6×6 Array{Bool,2}:
 false   true  false  false  false  false
 false  false  false   true   true  false
  true   true  false  false  false  false
 false  false  false  false   true   true
 false  false  false  false  false  false
 false  false  false  false   true  false

#### 4. Calculate a node outdegree using arclist

In [7]:
function find_outdegree(node,arcs)
  counter=0
  for i in arcs
    if i[1] == node
      counter+=1
    end
  end
  return counter
end

find_outdegree (generic function with 1 method)

In [8]:
arcs = [(1,2),(2,3),(2,4),(3,1),(3,2),(3,6),(4,5),(5,6)]

find_outdegree(2,arcs)

2

#### 5. Calculate a node outdegree using adjacency list

In [11]:
function find_outdegreeAdjList(node,adjList)
    return length(adjList[node])
end


find_outdegreeAdjList (generic function with 1 method)

In [14]:
find_outdegreeAdjList(2,adjList)

2

#### 6. Calculate a node indegree using incedence list


In [18]:
#First we construct an incedence list
#Then we create a function to calculate the indegree of a node

function constructIncListFromFile(fname)
    data=readcsv(fname,Int)
    n=maximum(data) #Assuming no gaps and starting from 1, this is the number of nodes
    m=size(data,1)
    A=Array(Array{Int},n) # Our adjacency list
    for i=1:n A[i]=[] end # Initialization of adjacency list
    # The main construction step
    for arcIndx=1:m
        i,j=data[arcIndx,:]
        push!(A[j],i)
    end
    A
end

constructIncListFromFile (generic function with 1 method)

.


In [24]:
incList = constructIncListFromFile("Lab_1_data.csv")

6-element Array{Array{Int64,N},1}:
 [3]    
 [1,3]  
 Int64[]
 [2]    
 [2,4,6]
 [4]    

In [29]:
function find_indegreeIncList(node,incList)
    return length(incList[node])
end

find_indegreeIncList (generic function with 1 method)

, Any) in module Main at In[27]:2 overwritten at In[29]:2.


In [31]:
find_indegreeIncList(5,incList)

3

#### 7. Calculate a node outdegree and indegree using adjacency matrix

In [33]:
function find_outdegreeMat(node,adjMatrix)
    return sum(adjMatrix[node,:])
end

function find_indegreeMat(node,adjMatrix)
    return sum(adjMatrix[:,node])
end


find_indegreeMat (generic function with 1 method)

In [35]:
find_outdegreeMat(4,adjMat)

2

In [36]:
find_indegreeMat(4,adjMat)

1

In [4]:
A=Array(Int,3)
A[2]=5
print(A)

[140639116528848,5,140639233789648]