# Search

We start by defining our network as an Adjececny List

In [8]:
adjL=[[2],
    [3,4,5],
    [1,5],
    [5,6],
    Int[],
    [5],
    [3,5]
]

7-element Array{Array{Int64,1},1}:
 [2]    
 [3,4,5]
 [1,5]  
 [5,6]  
 Int64[]
 [5]    
 [3,5]  

We need to create a logical function find an admissable arc

In [9]:
function find_addmissable(L,marked_list,tail)
    for head in L[tail]
        if !(head in marked_list)
            return head
        end
    end
    return -1 # Special value to indicate no addmissable arc 
end

find_addmissable (generic function with 1 method)

Next step is to write the search algorithm. 

In [24]:
function graph_search(s,aL,isDepth::Bool=true)
    # Initialization
    n=length(aL) #number of nodes 
    pred=zeros(Int,n)
    marked=Int[s]
    List=Int[s]
    # Now I can stard doing the actual work 
    while !isempty(List)
        i=isDepth? List[end]:List[1] #This is the current node
        j=find_addmissable(aL,marked,i)
        if j>0 # We found an addmissable arc 
            push!(marked,j)
            pred[j]=i
            push!(List,j)
        else
            isDepth? pop!(List):shift!(List)
        end
    end
    pred
end

graph_search (generic function with 2 methods)

In [25]:
graph_search(1,adjL,false) #Breadth

7-element Array{Int64,1}:
 0
 1
 2
 2
 2
 4
 0

In [26]:
graph_search(1,adjL) # Depth

7-element Array{Int64,1}:
 0
 1
 2
 2
 3
 4
 0

In [27]:
graph_search(7,adjL) # Depth

7-element Array{Int64,1}:
 3
 1
 7
 2
 4
 4
 0

In [31]:
Pkg.add("LightGraphs")

INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of LightGraphs
INFO: Use `Pkg.update()` to get the latest versions of your packages


Now we try to use and external library to do the same thing

In [32]:
using LightGraphs

INFO: Precompiling module LightGraphs.


In [36]:
g=DiGraph(7)
for i=1:length(adjL)
    for j in adjL[i]
        add_edge!(g,i,j)
    end
end

Now we do the depth first

In [37]:
dfs_tree(g, 1)

{7, 5} directed graph

In [38]:
bfs_tree(g,1)

{7, 5} directed graph

You should 
1. Fix out light graph definition error 
2. Check the time of our implimention with lightgraphs (e.g. @time bfs_tree(g,1))
3. Find a faster way to do the admissable arc computation
4. Repeat 2
